#!/bin/bash

echo "postinst"
ldconfig
systemctl daemon-reload
systemctl enable neuron
systemctl start neuron
(
sleep 3
if command -v apt-mark >/dev/null 2>&1; then  
    apt-mark hold neuron 
fi
) &

if [ -e "/etc/systemd/system/neuron.ekuiper.service" ]; then
  systemctl enable neuron.ekuiper
  systemctl start neuron.ekuiper
fi
