#!/bin/bash

echo "postinst"
ldconfig
systemctl daemon-reload
systemctl enable neuron
systemctl start neuron
(
sleep 3
apt-mark hold neuron
) &

if [ -e "/etc/systemd/system/neuron.ekuiper.service" ]; then
  systemctl enable neuron.ekuiper
  systemctl start neuron.ekuiper
fi
