#!/bin/bash

echo "prerm"

if [ -e "/etc/systemd/system/neuron.ekuiper.service" ]; then
  systemctl disable neuron.ekuiper
  systemctl stop neuron.ekuiper
fi

systemctl disable neuron
systemctl stop neuron
